export const DISPLAY_OPTION_DESCRIPTIONS = {
	text:                'Renders the field value as plain or formatted text.',
	image:               'Displays the field as an image element.',
	button:              'Renders a link field as a clickable button.',
	embed:               'Embeds media such as videos or external content inline from an oEmbed or URL field.',
	'embed-popup':       'Opens embedded media in a lightbox popup overlay. Visitors click a trigger to open the popup.',
	icon:                'Displays an icon picker field as an SVG icon.',
	map:                 'Renders a Google Map field as an interactive map.',
	'repeater-list':     'Loops through each repeater row in a vertical list layout. Insert ACF Sub-Field blocks inside to display and arrange sub fields for each row.',
	'repeater-grid':     'Loops through each repeater row in a multi-column grid layout. Insert ACF Sub-Field blocks inside to display and arrange sub fields for each row.',
	'repeater-carousel': 'Loops through each repeater row in a swipeable carousel. Insert ACF Sub-Field blocks inside to display and arrange sub fields for each row.',
	'repeater-accordion':'Loops through each repeater row as collapsible accordion sections. Insert ACF Sub-Field blocks inside to display and arrange sub fields for each row.',
	'repeater-tabs':     'Loops through each repeater row as switchable tab panels. Insert ACF Sub-Field blocks inside to display and arrange sub fields for each row.',
	'gallery-grid':      'Displays gallery images in a responsive grid with customizable columns and spacing.',
	'gallery-carousel':  'Displays gallery images in an interactive carousel with autoplay and transition options.',
	'gallery-masonry':   'Displays gallery images in a masonry layout that adapts to different image aspect ratios.',
	'post-list':         'Loops through each selected post in a vertical list, similar to the Query Loop. Insert blocks inside to display post title, content, featured image, or ACF fields from each post.',
	'post-grid':         'Loops through each selected post in a multi-column grid, similar to the Query Loop. Insert blocks inside to display post title, content, featured image, or ACF fields from each post.',
	'post-carousel':     'Loops through each selected post in a swipeable carousel. Insert blocks inside to display post title, content, featured image, or ACF fields from each post.',
	'single-post':       'Displays a single selected post. Insert blocks inside to display its title, content, featured image, or ACF fields.',
	'term-list':         'Loops through each selected term in a vertical list. Insert blocks inside to display term name, description, or ACF fields from each term.',
	'term-grid':         'Loops through each selected term in a multi-column grid. Insert blocks inside to display term name, description, or ACF fields from each term.',
	'term-carousel':     'Loops through each selected term in a swipeable carousel. Insert blocks inside to display term name, description, or ACF fields from each term.',
	'single-term':       'Displays a single selected term. Insert blocks inside to display its name, description, or ACF fields.',
	'user-list':         'Loops through each selected user in a vertical list. Insert blocks inside to display user name, avatar, bio, or ACF fields from each user.',
	'user-grid':         'Loops through each selected user in a multi-column grid. Insert blocks inside to display user name, avatar, bio, or ACF fields from each user.',
	'user-carousel':     'Loops through each selected user in a swipeable carousel. Insert blocks inside to display user name, avatar, bio, or ACF fields from each user.',
	'single-user':       'Displays a single selected user. Insert blocks inside to display their name, avatar, bio, or ACF fields.',
};

export const PRO_OPTIONS = new Set( [
	'embed-popup',
	'map',
	'repeater-list',
	'repeater-grid',
	'repeater-carousel',
	'repeater-accordion',
	'repeater-tabs',
	'gallery-grid',
	'gallery-carousel',
	'gallery-masonry',
	'post-list',
	'post-grid',
	'post-carousel',
	'term-list',
	'term-grid',
	'term-carousel',
	'user-list',
	'user-grid',
	'user-carousel',
] );
